package io.opencaesar.closeworld;

import io.opencaesar.closeworld.ClassExpression.*;
import org.junit.*;

import java.util.Arrays;
import java.util.HashSet;

import static org.junit.Assert.*;

public class TestClassExpression {
	private ClassExpression a, b, c;
	private ClassExpression dc, ec, fc;
	private ClassExpression gmh, imj, kml;
	private ClassExpression min, oip, qir;
	private ClassExpression sut, uuv, wux;
	private ClassExpression empty;
	private ClassExpression universal;

	@BeforeClass public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass public static void tearDownAfterClass() throws Exception {
	}

	@Before public void setUp() throws Exception {
		a = new Unitary("a");
		b = new Unitary("a");
		c = new Unitary("b");
		dc = new Unitary("d").complement();
		ec = new Unitary("e").complement();
		fc = new Unitary("f").complement();
		gmh = new Unitary("g").difference(new Unitary("h"));;
		imj = new Unitary("i").difference(new Unitary("j"));;
		kml = new Unitary("k").difference(new Unitary("l"));;
		min = new Unitary("m").intersection(new Unitary("n"));;
		oip = new Unitary("o").intersection(new Unitary("p"));;
		qir = new Unitary("q").intersection(new Unitary("r"));;
		sut = new Unitary("s").union(new Unitary("t"));;
		uuv = new Unitary("u").union(new Unitary("v"));;
		wux = new Unitary("w").union(new Unitary("x"));;
		empty = new Empty();
		universal = new Universal();
	}

	@After public void tearDown() throws Exception {
	}

	@Test public void testEqual() {
		assertEquals(a, a);
		assertNotEquals(a, dc);
		assertNotEquals(a, gmh);
		assertNotEquals(a, min);
		assertNotEquals(a, sut);
		assertNotEquals(a, empty);
		assertNotEquals(a, universal);
		assertNotEquals(dc, a);
		assertEquals(dc, dc);
		assertNotEquals(dc, gmh);
		assertNotEquals(dc, min);
		assertNotEquals(dc, sut);
		assertNotEquals(dc, empty);
		assertNotEquals(dc, universal);
		assertNotEquals(gmh, a);
		assertNotEquals(gmh, dc);
		assertEquals(gmh, gmh);
		assertNotEquals(gmh, min);
		assertNotEquals(gmh, sut);
		assertNotEquals(gmh, empty);
		assertNotEquals(gmh, universal);
		assertNotEquals(min, a);
		assertNotEquals(min, dc);
		assertNotEquals(min, gmh);
		assertEquals(min, min);
		assertNotEquals(min, sut);
		assertNotEquals(min, empty);
		assertNotEquals(min, universal);
		assertNotEquals(sut, a);
		assertNotEquals(sut, dc);
		assertNotEquals(sut, gmh);
		assertNotEquals(sut, min);
		assertEquals(sut, sut);
		assertNotEquals(sut, empty);
		assertNotEquals(sut, universal);
		assertNotEquals(empty, a);
		assertNotEquals(empty, dc);
		assertNotEquals(empty, gmh);
		assertNotEquals(empty, min);
		assertNotEquals(empty, sut);
		assertEquals(empty, empty);
		assertNotEquals(empty, universal);
		assertNotEquals(universal, a);
		assertNotEquals(universal, dc);
		assertNotEquals(universal, gmh);
		assertNotEquals(universal, min);
		assertNotEquals(universal, sut);
		assertNotEquals(universal, empty);
		assertEquals(universal, universal);
	}

	// Theorem 1: For any class A, (A′)′ = A.

	@Test public void testTheorem01() {
		assertEquals(a, a.complement().complement());;
		assertEquals(dc, dc.complement().complement());;
		assertEquals(gmh, gmh.complement().complement());;
		assertEquals(min, min.complement().complement());;
		assertEquals(sut, sut.complement().complement());;
		assertEquals(empty, empty.complement().complement());;
		assertEquals(universal, universal.complement().complement());;
	}

	// Theorem 2: For any class A, A ∩ A = A.

	@Test public void testTheorem02() {
		assertEquals(a, a.intersection(a));;
		assertEquals(dc, dc.intersection(dc));;
		assertEquals(gmh, gmh.intersection(gmh));;
		assertEquals(min, min.intersection(min));;
		assertEquals(sut, sut.intersection(sut));;
		assertEquals(empty, empty.intersection(empty));;
		assertEquals(universal, universal.intersection(universal));;
	}

	// Theorem 3: For any classes A and B, A ∩ B = B ∩ A.

	@Test public void testTheorem03() {
		assertEquals(b.intersection(a), a.intersection(b));
		assertEquals(ec.intersection(a), a.intersection(ec));
		assertEquals(imj.intersection(a), a.intersection(imj));
		assertEquals(oip.intersection(a), a.intersection(oip));
		assertEquals(uuv.intersection(a), a.intersection(uuv));
		assertEquals(empty.intersection(a), a.intersection(empty));
		assertEquals(universal.intersection(a), a.intersection(universal));
		assertEquals(b.intersection(dc), dc.intersection(b));
		assertEquals(ec.intersection(dc), dc.intersection(ec));
		assertEquals(imj.intersection(dc), dc.intersection(imj));
		assertEquals(oip.intersection(dc), dc.intersection(oip));
		assertEquals(uuv.intersection(dc), dc.intersection(uuv));
		assertEquals(empty.intersection(dc), dc.intersection(empty));
		assertEquals(universal.intersection(dc), dc.intersection(universal));
		assertEquals(b.intersection(gmh), gmh.intersection(b));
		assertEquals(ec.intersection(gmh), gmh.intersection(ec));
		assertEquals(imj.intersection(gmh), gmh.intersection(imj));
		assertEquals(oip.intersection(gmh), gmh.intersection(oip));
		assertEquals(uuv.intersection(gmh), gmh.intersection(uuv));
		assertEquals(empty.intersection(gmh), gmh.intersection(empty));
		assertEquals(universal.intersection(gmh), gmh.intersection(universal));
		assertEquals(b.intersection(min), min.intersection(b));
		assertEquals(ec.intersection(min), min.intersection(ec));
		assertEquals(imj.intersection(min), min.intersection(imj));
		assertEquals(oip.intersection(min), min.intersection(oip));
		assertEquals(uuv.intersection(min), min.intersection(uuv));
		assertEquals(empty.intersection(min), min.intersection(empty));
		assertEquals(universal.intersection(min), min.intersection(universal));
		assertEquals(b.intersection(sut), sut.intersection(b));
		assertEquals(ec.intersection(sut), sut.intersection(ec));
		assertEquals(imj.intersection(sut), sut.intersection(imj));
		assertEquals(oip.intersection(sut), sut.intersection(oip));
		assertEquals(uuv.intersection(sut), sut.intersection(uuv));
		assertEquals(empty.intersection(sut), sut.intersection(empty));
		assertEquals(universal.intersection(sut), sut.intersection(universal));
		assertEquals(b.intersection(empty), empty.intersection(b));
		assertEquals(ec.intersection(empty), empty.intersection(ec));
		assertEquals(imj.intersection(empty), empty.intersection(imj));
		assertEquals(oip.intersection(empty), empty.intersection(oip));
		assertEquals(uuv.intersection(empty), empty.intersection(uuv));
		assertEquals(empty.intersection(empty), empty.intersection(empty));
		assertEquals(universal.intersection(empty), empty.intersection(universal));
		assertEquals(b.intersection(universal), universal.intersection(b));
		assertEquals(ec.intersection(universal), universal.intersection(ec));
		assertEquals(imj.intersection(universal), universal.intersection(imj));
		assertEquals(oip.intersection(universal), universal.intersection(oip));
		assertEquals(uuv.intersection(universal), universal.intersection(uuv));
		assertEquals(empty.intersection(universal), universal.intersection(empty));
		assertEquals(universal.intersection(universal), universal.intersection(universal));
	}

	// Theorem 4: For any classes A, B, and C, (A ∩ B) ∩ C = A ∩ (B ∩ C).

	@Test public void testTheorem04() {
		assertEquals(a.intersection(b.intersection(c)), (a.intersection(b)).intersection(c));
		assertEquals(a.intersection(b.intersection(fc)), (a.intersection(b)).intersection(fc));
		assertEquals(a.intersection(b.intersection(kml)), (a.intersection(b)).intersection(kml));
		assertEquals(a.intersection(b.intersection(qir)), (a.intersection(b)).intersection(qir));
		assertEquals(a.intersection(b.intersection(wux)), (a.intersection(b)).intersection(wux));
		assertEquals(a.intersection(b.intersection(empty)), (a.intersection(b)).intersection(empty));
		assertEquals(a.intersection(b.intersection(universal)), (a.intersection(b)).intersection(universal));
		assertEquals(a.intersection(ec.intersection(c)), (a.intersection(ec)).intersection(c));
		assertEquals(a.intersection(ec.intersection(fc)), (a.intersection(ec)).intersection(fc));
		assertEquals(a.intersection(ec.intersection(kml)), (a.intersection(ec)).intersection(kml));
		assertEquals(a.intersection(ec.intersection(qir)), (a.intersection(ec)).intersection(qir));
		assertEquals(a.intersection(ec.intersection(wux)), (a.intersection(ec)).intersection(wux));
		assertEquals(a.intersection(ec.intersection(empty)), (a.intersection(ec)).intersection(empty));
		assertEquals(a.intersection(ec.intersection(universal)), (a.intersection(ec)).intersection(universal));
		assertEquals(a.intersection(imj.intersection(c)), (a.intersection(imj)).intersection(c));
		assertEquals(a.intersection(imj.intersection(fc)), (a.intersection(imj)).intersection(fc));
		assertEquals(a.intersection(imj.intersection(kml)), (a.intersection(imj)).intersection(kml));
		assertEquals(a.intersection(imj.intersection(qir)), (a.intersection(imj)).intersection(qir));
		assertEquals(a.intersection(imj.intersection(wux)), (a.intersection(imj)).intersection(wux));
		assertEquals(a.intersection(imj.intersection(empty)), (a.intersection(imj)).intersection(empty));
		assertEquals(a.intersection(imj.intersection(universal)), (a.intersection(imj)).intersection(universal));
		assertEquals(a.intersection(oip.intersection(c)), (a.intersection(oip)).intersection(c));
		assertEquals(a.intersection(oip.intersection(fc)), (a.intersection(oip)).intersection(fc));
		assertEquals(a.intersection(oip.intersection(kml)), (a.intersection(oip)).intersection(kml));
		assertEquals(a.intersection(oip.intersection(qir)), (a.intersection(oip)).intersection(qir));
		assertEquals(a.intersection(oip.intersection(wux)), (a.intersection(oip)).intersection(wux));
		assertEquals(a.intersection(oip.intersection(empty)), (a.intersection(oip)).intersection(empty));
		assertEquals(a.intersection(oip.intersection(universal)), (a.intersection(oip)).intersection(universal));
		assertEquals(a.intersection(uuv.intersection(c)), (a.intersection(uuv)).intersection(c));
		assertEquals(a.intersection(uuv.intersection(fc)), (a.intersection(uuv)).intersection(fc));
		assertEquals(a.intersection(uuv.intersection(kml)), (a.intersection(uuv)).intersection(kml));
		assertEquals(a.intersection(uuv.intersection(qir)), (a.intersection(uuv)).intersection(qir));
		assertEquals(a.intersection(uuv.intersection(wux)), (a.intersection(uuv)).intersection(wux));
		assertEquals(a.intersection(uuv.intersection(empty)), (a.intersection(uuv)).intersection(empty));
		assertEquals(a.intersection(uuv.intersection(universal)), (a.intersection(uuv)).intersection(universal));
		assertEquals(a.intersection(empty.intersection(c)), (a.intersection(empty)).intersection(c));
		assertEquals(a.intersection(empty.intersection(fc)), (a.intersection(empty)).intersection(fc));
		assertEquals(a.intersection(empty.intersection(kml)), (a.intersection(empty)).intersection(kml));
		assertEquals(a.intersection(empty.intersection(qir)), (a.intersection(empty)).intersection(qir));
		assertEquals(a.intersection(empty.intersection(wux)), (a.intersection(empty)).intersection(wux));
		assertEquals(a.intersection(empty.intersection(empty)), (a.intersection(empty)).intersection(empty));
		assertEquals(a.intersection(empty.intersection(universal)), (a.intersection(empty)).intersection(universal));
		assertEquals(a.intersection(universal.intersection(c)), (a.intersection(universal)).intersection(c));
		assertEquals(a.intersection(universal.intersection(fc)), (a.intersection(universal)).intersection(fc));
		assertEquals(a.intersection(universal.intersection(kml)), (a.intersection(universal)).intersection(kml));
		assertEquals(a.intersection(universal.intersection(qir)), (a.intersection(universal)).intersection(qir));
		assertEquals(a.intersection(universal.intersection(wux)), (a.intersection(universal)).intersection(wux));
		assertEquals(a.intersection(universal.intersection(empty)), (a.intersection(universal)).intersection(empty));
		assertEquals(a.intersection(universal.intersection(universal)), (a.intersection(universal)).intersection(universal));
		assertEquals(dc.intersection(b.intersection(c)), (dc.intersection(b)).intersection(c));
		assertEquals(dc.intersection(b.intersection(fc)), (dc.intersection(b)).intersection(fc));
		assertEquals(dc.intersection(b.intersection(kml)), (dc.intersection(b)).intersection(kml));
		assertEquals(dc.intersection(b.intersection(qir)), (dc.intersection(b)).intersection(qir));
		assertEquals(dc.intersection(b.intersection(wux)), (dc.intersection(b)).intersection(wux));
		assertEquals(dc.intersection(b.intersection(empty)), (dc.intersection(b)).intersection(empty));
		assertEquals(dc.intersection(b.intersection(universal)), (dc.intersection(b)).intersection(universal));
		assertEquals(dc.intersection(ec.intersection(c)), (dc.intersection(ec)).intersection(c));
		assertEquals(dc.intersection(ec.intersection(fc)), (dc.intersection(ec)).intersection(fc));
		assertEquals(dc.intersection(ec.intersection(kml)), (dc.intersection(ec)).intersection(kml));
		assertEquals(dc.intersection(ec.intersection(qir)), (dc.intersection(ec)).intersection(qir));
		assertEquals(dc.intersection(ec.intersection(wux)), (dc.intersection(ec)).intersection(wux));
		assertEquals(dc.intersection(ec.intersection(empty)), (dc.intersection(ec)).intersection(empty));
		assertEquals(dc.intersection(ec.intersection(universal)), (dc.intersection(ec)).intersection(universal));
		assertEquals(dc.intersection(imj.intersection(c)), (dc.intersection(imj)).intersection(c));
		assertEquals(dc.intersection(imj.intersection(fc)), (dc.intersection(imj)).intersection(fc));
		assertEquals(dc.intersection(imj.intersection(kml)), (dc.intersection(imj)).intersection(kml));
		assertEquals(dc.intersection(imj.intersection(qir)), (dc.intersection(imj)).intersection(qir));
		assertEquals(dc.intersection(imj.intersection(wux)), (dc.intersection(imj)).intersection(wux));
		assertEquals(dc.intersection(imj.intersection(empty)), (dc.intersection(imj)).intersection(empty));
		assertEquals(dc.intersection(imj.intersection(universal)), (dc.intersection(imj)).intersection(universal));
		assertEquals(dc.intersection(oip.intersection(c)), (dc.intersection(oip)).intersection(c));
		assertEquals(dc.intersection(oip.intersection(fc)), (dc.intersection(oip)).intersection(fc));
		assertEquals(dc.intersection(oip.intersection(kml)), (dc.intersection(oip)).intersection(kml));
		assertEquals(dc.intersection(oip.intersection(qir)), (dc.intersection(oip)).intersection(qir));
		assertEquals(dc.intersection(oip.intersection(wux)), (dc.intersection(oip)).intersection(wux));
		assertEquals(dc.intersection(oip.intersection(empty)), (dc.intersection(oip)).intersection(empty));
		assertEquals(dc.intersection(oip.intersection(universal)), (dc.intersection(oip)).intersection(universal));
		assertEquals(dc.intersection(uuv.intersection(c)), (dc.intersection(uuv)).intersection(c));
		assertEquals(dc.intersection(uuv.intersection(fc)), (dc.intersection(uuv)).intersection(fc));
		assertEquals(dc.intersection(uuv.intersection(kml)), (dc.intersection(uuv)).intersection(kml));
		assertEquals(dc.intersection(uuv.intersection(qir)), (dc.intersection(uuv)).intersection(qir));
		assertEquals(dc.intersection(uuv.intersection(wux)), (dc.intersection(uuv)).intersection(wux));
		assertEquals(dc.intersection(uuv.intersection(empty)), (dc.intersection(uuv)).intersection(empty));
		assertEquals(dc.intersection(uuv.intersection(universal)), (dc.intersection(uuv)).intersection(universal));
		assertEquals(dc.intersection(empty.intersection(c)), (dc.intersection(empty)).intersection(c));
		assertEquals(dc.intersection(empty.intersection(fc)), (dc.intersection(empty)).intersection(fc));
		assertEquals(dc.intersection(empty.intersection(kml)), (dc.intersection(empty)).intersection(kml));
		assertEquals(dc.intersection(empty.intersection(qir)), (dc.intersection(empty)).intersection(qir));
		assertEquals(dc.intersection(empty.intersection(wux)), (dc.intersection(empty)).intersection(wux));
		assertEquals(dc.intersection(empty.intersection(empty)), (dc.intersection(empty)).intersection(empty));
		assertEquals(dc.intersection(empty.intersection(universal)), (dc.intersection(empty)).intersection(universal));
		assertEquals(dc.intersection(universal.intersection(c)), (dc.intersection(universal)).intersection(c));
		assertEquals(dc.intersection(universal.intersection(fc)), (dc.intersection(universal)).intersection(fc));
		assertEquals(dc.intersection(universal.intersection(kml)), (dc.intersection(universal)).intersection(kml));
		assertEquals(dc.intersection(universal.intersection(qir)), (dc.intersection(universal)).intersection(qir));
		assertEquals(dc.intersection(universal.intersection(wux)), (dc.intersection(universal)).intersection(wux));
		assertEquals(dc.intersection(universal.intersection(empty)), (dc.intersection(universal)).intersection(empty));
		assertEquals(dc.intersection(universal.intersection(universal)), (dc.intersection(universal)).intersection(universal));
		assertEquals(gmh.intersection(b.intersection(c)), (gmh.intersection(b)).intersection(c));
		assertEquals(gmh.intersection(b.intersection(fc)), (gmh.intersection(b)).intersection(fc));
		assertEquals(gmh.intersection(b.intersection(kml)), (gmh.intersection(b)).intersection(kml));
		assertEquals(gmh.intersection(b.intersection(qir)), (gmh.intersection(b)).intersection(qir));
		assertEquals(gmh.intersection(b.intersection(wux)), (gmh.intersection(b)).intersection(wux));
		assertEquals(gmh.intersection(b.intersection(empty)), (gmh.intersection(b)).intersection(empty));
		assertEquals(gmh.intersection(b.intersection(universal)), (gmh.intersection(b)).intersection(universal));
		assertEquals(gmh.intersection(ec.intersection(c)), (gmh.intersection(ec)).intersection(c));
		assertEquals(gmh.intersection(ec.intersection(fc)), (gmh.intersection(ec)).intersection(fc));
		assertEquals(gmh.intersection(ec.intersection(kml)), (gmh.intersection(ec)).intersection(kml));
		assertEquals(gmh.intersection(ec.intersection(qir)), (gmh.intersection(ec)).intersection(qir));
		assertEquals(gmh.intersection(ec.intersection(wux)), (gmh.intersection(ec)).intersection(wux));
		assertEquals(gmh.intersection(ec.intersection(empty)), (gmh.intersection(ec)).intersection(empty));
		assertEquals(gmh.intersection(ec.intersection(universal)), (gmh.intersection(ec)).intersection(universal));
		assertEquals(gmh.intersection(imj.intersection(c)), (gmh.intersection(imj)).intersection(c));
		assertEquals(gmh.intersection(imj.intersection(fc)), (gmh.intersection(imj)).intersection(fc));
		assertEquals(gmh.intersection(imj.intersection(kml)), (gmh.intersection(imj)).intersection(kml));
		assertEquals(gmh.intersection(imj.intersection(qir)), (gmh.intersection(imj)).intersection(qir));
		assertEquals(gmh.intersection(imj.intersection(wux)), (gmh.intersection(imj)).intersection(wux));
		assertEquals(gmh.intersection(imj.intersection(empty)), (gmh.intersection(imj)).intersection(empty));
		assertEquals(gmh.intersection(imj.intersection(universal)), (gmh.intersection(imj)).intersection(universal));
		assertEquals(gmh.intersection(oip.intersection(c)), (gmh.intersection(oip)).intersection(c));
		assertEquals(gmh.intersection(oip.intersection(fc)), (gmh.intersection(oip)).intersection(fc));
		assertEquals(gmh.intersection(oip.intersection(kml)), (gmh.intersection(oip)).intersection(kml));
		assertEquals(gmh.intersection(oip.intersection(qir)), (gmh.intersection(oip)).intersection(qir));
		assertEquals(gmh.intersection(oip.intersection(wux)), (gmh.intersection(oip)).intersection(wux));
		assertEquals(gmh.intersection(oip.intersection(empty)), (gmh.intersection(oip)).intersection(empty));
		assertEquals(gmh.intersection(oip.intersection(universal)), (gmh.intersection(oip)).intersection(universal));
		assertEquals(gmh.intersection(uuv.intersection(c)), (gmh.intersection(uuv)).intersection(c));
		assertEquals(gmh.intersection(uuv.intersection(fc)), (gmh.intersection(uuv)).intersection(fc));
		assertEquals(gmh.intersection(uuv.intersection(kml)), (gmh.intersection(uuv)).intersection(kml));
		assertEquals(gmh.intersection(uuv.intersection(qir)), (gmh.intersection(uuv)).intersection(qir));
		assertEquals(gmh.intersection(uuv.intersection(wux)), (gmh.intersection(uuv)).intersection(wux));
		assertEquals(gmh.intersection(uuv.intersection(empty)), (gmh.intersection(uuv)).intersection(empty));
		assertEquals(gmh.intersection(uuv.intersection(universal)), (gmh.intersection(uuv)).intersection(universal));
		assertEquals(gmh.intersection(empty.intersection(c)), (gmh.intersection(empty)).intersection(c));
		assertEquals(gmh.intersection(empty.intersection(fc)), (gmh.intersection(empty)).intersection(fc));
		assertEquals(gmh.intersection(empty.intersection(kml)), (gmh.intersection(empty)).intersection(kml));
		assertEquals(gmh.intersection(empty.intersection(qir)), (gmh.intersection(empty)).intersection(qir));
		assertEquals(gmh.intersection(empty.intersection(wux)), (gmh.intersection(empty)).intersection(wux));
		assertEquals(gmh.intersection(empty.intersection(empty)), (gmh.intersection(empty)).intersection(empty));
		assertEquals(gmh.intersection(empty.intersection(universal)), (gmh.intersection(empty)).intersection(universal));
		assertEquals(gmh.intersection(universal.intersection(c)), (gmh.intersection(universal)).intersection(c));
		assertEquals(gmh.intersection(universal.intersection(fc)), (gmh.intersection(universal)).intersection(fc));
		assertEquals(gmh.intersection(universal.intersection(kml)), (gmh.intersection(universal)).intersection(kml));
		assertEquals(gmh.intersection(universal.intersection(qir)), (gmh.intersection(universal)).intersection(qir));
		assertEquals(gmh.intersection(universal.intersection(wux)), (gmh.intersection(universal)).intersection(wux));
		assertEquals(gmh.intersection(universal.intersection(empty)), (gmh.intersection(universal)).intersection(empty));
		assertEquals(gmh.intersection(universal.intersection(universal)), (gmh.intersection(universal)).intersection(universal));
		assertEquals(min.intersection(b.intersection(c)), (min.intersection(b)).intersection(c));
		assertEquals(min.intersection(b.intersection(fc)), (min.intersection(b)).intersection(fc));
		assertEquals(min.intersection(b.intersection(kml)), (min.intersection(b)).intersection(kml));
		assertEquals(min.intersection(b.intersection(qir)), (min.intersection(b)).intersection(qir));
		assertEquals(min.intersection(b.intersection(wux)), (min.intersection(b)).intersection(wux));
		assertEquals(min.intersection(b.intersection(empty)), (min.intersection(b)).intersection(empty));
		assertEquals(min.intersection(b.intersection(universal)), (min.intersection(b)).intersection(universal));
		assertEquals(min.intersection(ec.intersection(c)), (min.intersection(ec)).intersection(c));
		assertEquals(min.intersection(ec.intersection(fc)), (min.intersection(ec)).intersection(fc));
		assertEquals(min.intersection(ec.intersection(kml)), (min.intersection(ec)).intersection(kml));
		assertEquals(min.intersection(ec.intersection(qir)), (min.intersection(ec)).intersection(qir));
		assertEquals(min.intersection(ec.intersection(wux)), (min.intersection(ec)).intersection(wux));
		assertEquals(min.intersection(ec.intersection(empty)), (min.intersection(ec)).intersection(empty));
		assertEquals(min.intersection(ec.intersection(universal)), (min.intersection(ec)).intersection(universal));
		assertEquals(min.intersection(imj.intersection(c)), (min.intersection(imj)).intersection(c));
		assertEquals(min.intersection(imj.intersection(fc)), (min.intersection(imj)).intersection(fc));
		assertEquals(min.intersection(imj.intersection(kml)), (min.intersection(imj)).intersection(kml));
		assertEquals(min.intersection(imj.intersection(qir)), (min.intersection(imj)).intersection(qir));
		assertEquals(min.intersection(imj.intersection(wux)), (min.intersection(imj)).intersection(wux));
		assertEquals(min.intersection(imj.intersection(empty)), (min.intersection(imj)).intersection(empty));
		assertEquals(min.intersection(imj.intersection(universal)), (min.intersection(imj)).intersection(universal));
		assertEquals(min.intersection(oip.intersection(c)), (min.intersection(oip)).intersection(c));
		assertEquals(min.intersection(oip.intersection(fc)), (min.intersection(oip)).intersection(fc));
		assertEquals(min.intersection(oip.intersection(kml)), (min.intersection(oip)).intersection(kml));
		assertEquals(min.intersection(oip.intersection(qir)), (min.intersection(oip)).intersection(qir));
		assertEquals(min.intersection(oip.intersection(wux)), (min.intersection(oip)).intersection(wux));
		assertEquals(min.intersection(oip.intersection(empty)), (min.intersection(oip)).intersection(empty));
		assertEquals(min.intersection(oip.intersection(universal)), (min.intersection(oip)).intersection(universal));
		assertEquals(min.intersection(uuv.intersection(c)), (min.intersection(uuv)).intersection(c));
		assertEquals(min.intersection(uuv.intersection(fc)), (min.intersection(uuv)).intersection(fc));
		assertEquals(min.intersection(uuv.intersection(kml)), (min.intersection(uuv)).intersection(kml));
		assertEquals(min.intersection(uuv.intersection(qir)), (min.intersection(uuv)).intersection(qir));
		assertEquals(min.intersection(uuv.intersection(wux)), (min.intersection(uuv)).intersection(wux));
		assertEquals(min.intersection(uuv.intersection(empty)), (min.intersection(uuv)).intersection(empty));
		assertEquals(min.intersection(uuv.intersection(universal)), (min.intersection(uuv)).intersection(universal));
		assertEquals(min.intersection(empty.intersection(c)), (min.intersection(empty)).intersection(c));
		assertEquals(min.intersection(empty.intersection(fc)), (min.intersection(empty)).intersection(fc));
		assertEquals(min.intersection(empty.intersection(kml)), (min.intersection(empty)).intersection(kml));
		assertEquals(min.intersection(empty.intersection(qir)), (min.intersection(empty)).intersection(qir));
		assertEquals(min.intersection(empty.intersection(wux)), (min.intersection(empty)).intersection(wux));
		assertEquals(min.intersection(empty.intersection(empty)), (min.intersection(empty)).intersection(empty));
		assertEquals(min.intersection(empty.intersection(universal)), (min.intersection(empty)).intersection(universal));
		assertEquals(min.intersection(universal.intersection(c)), (min.intersection(universal)).intersection(c));
		assertEquals(min.intersection(universal.intersection(fc)), (min.intersection(universal)).intersection(fc));
		assertEquals(min.intersection(universal.intersection(kml)), (min.intersection(universal)).intersection(kml));
		assertEquals(min.intersection(universal.intersection(qir)), (min.intersection(universal)).intersection(qir));
		assertEquals(min.intersection(universal.intersection(wux)), (min.intersection(universal)).intersection(wux));
		assertEquals(min.intersection(universal.intersection(empty)), (min.intersection(universal)).intersection(empty));
		assertEquals(min.intersection(universal.intersection(universal)), (min.intersection(universal)).intersection(universal));
		assertEquals(sut.intersection(b.intersection(c)), (sut.intersection(b)).intersection(c));
		assertEquals(sut.intersection(b.intersection(fc)), (sut.intersection(b)).intersection(fc));
		assertEquals(sut.intersection(b.intersection(kml)), (sut.intersection(b)).intersection(kml));
		assertEquals(sut.intersection(b.intersection(qir)), (sut.intersection(b)).intersection(qir));
		assertEquals(sut.intersection(b.intersection(wux)), (sut.intersection(b)).intersection(wux));
		assertEquals(sut.intersection(b.intersection(empty)), (sut.intersection(b)).intersection(empty));
		assertEquals(sut.intersection(b.intersection(universal)), (sut.intersection(b)).intersection(universal));
		assertEquals(sut.intersection(ec.intersection(c)), (sut.intersection(ec)).intersection(c));
		assertEquals(sut.intersection(ec.intersection(fc)), (sut.intersection(ec)).intersection(fc));
		assertEquals(sut.intersection(ec.intersection(kml)), (sut.intersection(ec)).intersection(kml));
		assertEquals(sut.intersection(ec.intersection(qir)), (sut.intersection(ec)).intersection(qir));
		assertEquals(sut.intersection(ec.intersection(wux)), (sut.intersection(ec)).intersection(wux));
		assertEquals(sut.intersection(ec.intersection(empty)), (sut.intersection(ec)).intersection(empty));
		assertEquals(sut.intersection(ec.intersection(universal)), (sut.intersection(ec)).intersection(universal));
		assertEquals(sut.intersection(imj.intersection(c)), (sut.intersection(imj)).intersection(c));
		assertEquals(sut.intersection(imj.intersection(fc)), (sut.intersection(imj)).intersection(fc));
		assertEquals(sut.intersection(imj.intersection(kml)), (sut.intersection(imj)).intersection(kml));
		assertEquals(sut.intersection(imj.intersection(qir)), (sut.intersection(imj)).intersection(qir));
		assertEquals(sut.intersection(imj.intersection(wux)), (sut.intersection(imj)).intersection(wux));
		assertEquals(sut.intersection(imj.intersection(empty)), (sut.intersection(imj)).intersection(empty));
		assertEquals(sut.intersection(imj.intersection(universal)), (sut.intersection(imj)).intersection(universal));
		assertEquals(sut.intersection(oip.intersection(c)), (sut.intersection(oip)).intersection(c));
		assertEquals(sut.intersection(oip.intersection(fc)), (sut.intersection(oip)).intersection(fc));
		assertEquals(sut.intersection(oip.intersection(kml)), (sut.intersection(oip)).intersection(kml));
		assertEquals(sut.intersection(oip.intersection(qir)), (sut.intersection(oip)).intersection(qir));
		assertEquals(sut.intersection(oip.intersection(wux)), (sut.intersection(oip)).intersection(wux));
		assertEquals(sut.intersection(oip.intersection(empty)), (sut.intersection(oip)).intersection(empty));
		assertEquals(sut.intersection(oip.intersection(universal)), (sut.intersection(oip)).intersection(universal));
		assertEquals(sut.intersection(uuv.intersection(c)), (sut.intersection(uuv)).intersection(c));
		assertEquals(sut.intersection(uuv.intersection(fc)), (sut.intersection(uuv)).intersection(fc));
		assertEquals(sut.intersection(uuv.intersection(kml)), (sut.intersection(uuv)).intersection(kml));
		assertEquals(sut.intersection(uuv.intersection(qir)), (sut.intersection(uuv)).intersection(qir));
		assertEquals(sut.intersection(uuv.intersection(wux)), (sut.intersection(uuv)).intersection(wux));
		assertEquals(sut.intersection(uuv.intersection(empty)), (sut.intersection(uuv)).intersection(empty));
		assertEquals(sut.intersection(uuv.intersection(universal)), (sut.intersection(uuv)).intersection(universal));
		assertEquals(sut.intersection(empty.intersection(c)), (sut.intersection(empty)).intersection(c));
		assertEquals(sut.intersection(empty.intersection(fc)), (sut.intersection(empty)).intersection(fc));
		assertEquals(sut.intersection(empty.intersection(kml)), (sut.intersection(empty)).intersection(kml));
		assertEquals(sut.intersection(empty.intersection(qir)), (sut.intersection(empty)).intersection(qir));
		assertEquals(sut.intersection(empty.intersection(wux)), (sut.intersection(empty)).intersection(wux));
		assertEquals(sut.intersection(empty.intersection(empty)), (sut.intersection(empty)).intersection(empty));
		assertEquals(sut.intersection(empty.intersection(universal)), (sut.intersection(empty)).intersection(universal));
		assertEquals(sut.intersection(universal.intersection(c)), (sut.intersection(universal)).intersection(c));
		assertEquals(sut.intersection(universal.intersection(fc)), (sut.intersection(universal)).intersection(fc));
		assertEquals(sut.intersection(universal.intersection(kml)), (sut.intersection(universal)).intersection(kml));
		assertEquals(sut.intersection(universal.intersection(qir)), (sut.intersection(universal)).intersection(qir));
		assertEquals(sut.intersection(universal.intersection(wux)), (sut.intersection(universal)).intersection(wux));
		assertEquals(sut.intersection(universal.intersection(empty)), (sut.intersection(universal)).intersection(empty));
		assertEquals(sut.intersection(universal.intersection(universal)), (sut.intersection(universal)).intersection(universal));
		assertEquals(empty.intersection(b.intersection(c)), (empty.intersection(b)).intersection(c));
		assertEquals(empty.intersection(b.intersection(fc)), (empty.intersection(b)).intersection(fc));
		assertEquals(empty.intersection(b.intersection(kml)), (empty.intersection(b)).intersection(kml));
		assertEquals(empty.intersection(b.intersection(qir)), (empty.intersection(b)).intersection(qir));
		assertEquals(empty.intersection(b.intersection(wux)), (empty.intersection(b)).intersection(wux));
		assertEquals(empty.intersection(b.intersection(empty)), (empty.intersection(b)).intersection(empty));
		assertEquals(empty.intersection(b.intersection(universal)), (empty.intersection(b)).intersection(universal));
		assertEquals(empty.intersection(ec.intersection(c)), (empty.intersection(ec)).intersection(c));
		assertEquals(empty.intersection(ec.intersection(fc)), (empty.intersection(ec)).intersection(fc));
		assertEquals(empty.intersection(ec.intersection(kml)), (empty.intersection(ec)).intersection(kml));
		assertEquals(empty.intersection(ec.intersection(qir)), (empty.intersection(ec)).intersection(qir));
		assertEquals(empty.intersection(ec.intersection(wux)), (empty.intersection(ec)).intersection(wux));
		assertEquals(empty.intersection(ec.intersection(empty)), (empty.intersection(ec)).intersection(empty));
		assertEquals(empty.intersection(ec.intersection(universal)), (empty.intersection(ec)).intersection(universal));
		assertEquals(empty.intersection(imj.intersection(c)), (empty.intersection(imj)).intersection(c));
		assertEquals(empty.intersection(imj.intersection(fc)), (empty.intersection(imj)).intersection(fc));
		assertEquals(empty.intersection(imj.intersection(kml)), (empty.intersection(imj)).intersection(kml));
		assertEquals(empty.intersection(imj.intersection(qir)), (empty.intersection(imj)).intersection(qir));
		assertEquals(empty.intersection(imj.intersection(wux)), (empty.intersection(imj)).intersection(wux));
		assertEquals(empty.intersection(imj.intersection(empty)), (empty.intersection(imj)).intersection(empty));
		assertEquals(empty.intersection(imj.intersection(universal)), (empty.intersection(imj)).intersection(universal));
		assertEquals(empty.intersection(oip.intersection(c)), (empty.intersection(oip)).intersection(c));
		assertEquals(empty.intersection(oip.intersection(fc)), (empty.intersection(oip)).intersection(fc));
		assertEquals(empty.intersection(oip.intersection(kml)), (empty.intersection(oip)).intersection(kml));
		assertEquals(empty.intersection(oip.intersection(qir)), (empty.intersection(oip)).intersection(qir));
		assertEquals(empty.intersection(oip.intersection(wux)), (empty.intersection(oip)).intersection(wux));
		assertEquals(empty.intersection(oip.intersection(empty)), (empty.intersection(oip)).intersection(empty));
		assertEquals(empty.intersection(oip.intersection(universal)), (empty.intersection(oip)).intersection(universal));
		assertEquals(empty.intersection(uuv.intersection(c)), (empty.intersection(uuv)).intersection(c));
		assertEquals(empty.intersection(uuv.intersection(fc)), (empty.intersection(uuv)).intersection(fc));
		assertEquals(empty.intersection(uuv.intersection(kml)), (empty.intersection(uuv)).intersection(kml));
		assertEquals(empty.intersection(uuv.intersection(qir)), (empty.intersection(uuv)).intersection(qir));
		assertEquals(empty.intersection(uuv.intersection(wux)), (empty.intersection(uuv)).intersection(wux));
		assertEquals(empty.intersection(uuv.intersection(empty)), (empty.intersection(uuv)).intersection(empty));
		assertEquals(empty.intersection(uuv.intersection(universal)), (empty.intersection(uuv)).intersection(universal));
		assertEquals(empty.intersection(empty.intersection(c)), (empty.intersection(empty)).intersection(c));
		assertEquals(empty.intersection(empty.intersection(fc)), (empty.intersection(empty)).intersection(fc));
		assertEquals(empty.intersection(empty.intersection(kml)), (empty.intersection(empty)).intersection(kml));
		assertEquals(empty.intersection(empty.intersection(qir)), (empty.intersection(empty)).intersection(qir));
		assertEquals(empty.intersection(empty.intersection(wux)), (empty.intersection(empty)).intersection(wux));
		assertEquals(empty.intersection(empty.intersection(empty)), (empty.intersection(empty)).intersection(empty));
		assertEquals(empty.intersection(empty.intersection(universal)), (empty.intersection(empty)).intersection(universal));
		assertEquals(empty.intersection(universal.intersection(c)), (empty.intersection(universal)).intersection(c));
		assertEquals(empty.intersection(universal.intersection(fc)), (empty.intersection(universal)).intersection(fc));
		assertEquals(empty.intersection(universal.intersection(kml)), (empty.intersection(universal)).intersection(kml));
		assertEquals(empty.intersection(universal.intersection(qir)), (empty.intersection(universal)).intersection(qir));
		assertEquals(empty.intersection(universal.intersection(wux)), (empty.intersection(universal)).intersection(wux));
		assertEquals(empty.intersection(universal.intersection(empty)), (empty.intersection(universal)).intersection(empty));
		assertEquals(empty.intersection(universal.intersection(universal)), (empty.intersection(universal)).intersection(universal));
		assertEquals(universal.intersection(b.intersection(c)), (universal.intersection(b)).intersection(c));
		assertEquals(universal.intersection(b.intersection(fc)), (universal.intersection(b)).intersection(fc));
		assertEquals(universal.intersection(b.intersection(kml)), (universal.intersection(b)).intersection(kml));
		assertEquals(universal.intersection(b.intersection(qir)), (universal.intersection(b)).intersection(qir));
		assertEquals(universal.intersection(b.intersection(wux)), (universal.intersection(b)).intersection(wux));
		assertEquals(universal.intersection(b.intersection(empty)), (universal.intersection(b)).intersection(empty));
		assertEquals(universal.intersection(b.intersection(universal)), (universal.intersection(b)).intersection(universal));
		assertEquals(universal.intersection(ec.intersection(c)), (universal.intersection(ec)).intersection(c));
		assertEquals(universal.intersection(ec.intersection(fc)), (universal.intersection(ec)).intersection(fc));
		assertEquals(universal.intersection(ec.intersection(kml)), (universal.intersection(ec)).intersection(kml));
		assertEquals(universal.intersection(ec.intersection(qir)), (universal.intersection(ec)).intersection(qir));
		assertEquals(universal.intersection(ec.intersection(wux)), (universal.intersection(ec)).intersection(wux));
		assertEquals(universal.intersection(ec.intersection(empty)), (universal.intersection(ec)).intersection(empty));
		assertEquals(universal.intersection(ec.intersection(universal)), (universal.intersection(ec)).intersection(universal));
		assertEquals(universal.intersection(imj.intersection(c)), (universal.intersection(imj)).intersection(c));
		assertEquals(universal.intersection(imj.intersection(fc)), (universal.intersection(imj)).intersection(fc));
		assertEquals(universal.intersection(imj.intersection(kml)), (universal.intersection(imj)).intersection(kml));
		assertEquals(universal.intersection(imj.intersection(qir)), (universal.intersection(imj)).intersection(qir));
		assertEquals(universal.intersection(imj.intersection(wux)), (universal.intersection(imj)).intersection(wux));
		assertEquals(universal.intersection(imj.intersection(empty)), (universal.intersection(imj)).intersection(empty));
		assertEquals(universal.intersection(imj.intersection(universal)), (universal.intersection(imj)).intersection(universal));
		assertEquals(universal.intersection(oip.intersection(c)), (universal.intersection(oip)).intersection(c));
		assertEquals(universal.intersection(oip.intersection(fc)), (universal.intersection(oip)).intersection(fc));
		assertEquals(universal.intersection(oip.intersection(kml)), (universal.intersection(oip)).intersection(kml));
		assertEquals(universal.intersection(oip.intersection(qir)), (universal.intersection(oip)).intersection(qir));
		assertEquals(universal.intersection(oip.intersection(wux)), (universal.intersection(oip)).intersection(wux));
		assertEquals(universal.intersection(oip.intersection(empty)), (universal.intersection(oip)).intersection(empty));
		assertEquals(universal.intersection(oip.intersection(universal)), (universal.intersection(oip)).intersection(universal));
		assertEquals(universal.intersection(uuv.intersection(c)), (universal.intersection(uuv)).intersection(c));
		assertEquals(universal.intersection(uuv.intersection(fc)), (universal.intersection(uuv)).intersection(fc));
		assertEquals(universal.intersection(uuv.intersection(kml)), (universal.intersection(uuv)).intersection(kml));
		assertEquals(universal.intersection(uuv.intersection(qir)), (universal.intersection(uuv)).intersection(qir));
		assertEquals(universal.intersection(uuv.intersection(wux)), (universal.intersection(uuv)).intersection(wux));
		assertEquals(universal.intersection(uuv.intersection(empty)), (universal.intersection(uuv)).intersection(empty));
		assertEquals(universal.intersection(uuv.intersection(universal)), (universal.intersection(uuv)).intersection(universal));
		assertEquals(universal.intersection(empty.intersection(c)), (universal.intersection(empty)).intersection(c));
		assertEquals(universal.intersection(empty.intersection(fc)), (universal.intersection(empty)).intersection(fc));
		assertEquals(universal.intersection(empty.intersection(kml)), (universal.intersection(empty)).intersection(kml));
		assertEquals(universal.intersection(empty.intersection(qir)), (universal.intersection(empty)).intersection(qir));
		assertEquals(universal.intersection(empty.intersection(wux)), (universal.intersection(empty)).intersection(wux));
		assertEquals(universal.intersection(empty.intersection(empty)), (universal.intersection(empty)).intersection(empty));
		assertEquals(universal.intersection(empty.intersection(universal)), (universal.intersection(empty)).intersection(universal));
		assertEquals(universal.intersection(universal.intersection(c)), (universal.intersection(universal)).intersection(c));
		assertEquals(universal.intersection(universal.intersection(fc)), (universal.intersection(universal)).intersection(fc));
		assertEquals(universal.intersection(universal.intersection(kml)), (universal.intersection(universal)).intersection(kml));
		assertEquals(universal.intersection(universal.intersection(qir)), (universal.intersection(universal)).intersection(qir));
		assertEquals(universal.intersection(universal.intersection(wux)), (universal.intersection(universal)).intersection(wux));
		assertEquals(universal.intersection(universal.intersection(empty)), (universal.intersection(universal)).intersection(empty));
		assertEquals(universal.intersection(universal.intersection(universal)), (universal.intersection(universal)).intersection(universal));
	}
	
	// Theorem 5: For any class A, A ∪ A = A.

	@Test public void testTheorem05() {
	    assertEquals(a, a.union(a));
	    assertEquals(dc, dc.union(dc));
	    assertEquals(gmh, gmh.union(gmh));
	    assertEquals(min, min.union(min));
	    assertEquals(sut, sut.union(sut));
	    assertEquals(empty, empty.union(empty));
	    assertEquals(universal, universal.union(universal));
	}

}
