PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?key ?value WHERE {
  ? <http://opencaesar.io/document#includes> ?key .
  ?key a ?value .
  ?value rdfs:subClassOf <http://opencaesar.io/document#Element>
}